AWSTemplateFormatVersion: 2010-09-09
Description: Spam Ham
Parameters:
  PredictionEndpoint:
    Type: String
Resources:
  asm3emailfiles:
    Type: AWS::S3::Bucket
    DependsOn:
      - LambdaPermission
    Properties:
      AccessControl: PublicRead
      BucketName: asm3emailfiles
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt lf1spamham.Arn
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "*"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref asm3emailfiles
                - /*
      Bucket: !Ref asm3emailfiles
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref lf1spamham
      Principal: s3.amazonaws.com
  lf1spamhamrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lf1spamhamrole
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/CloudWatchEventsFullAccess
      Path: /
  LambdaLayer1:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: lambdas-cloudformation
        S3Key: asm3-lf1-numpy-5391633b-8540-46f4-9de4-12399965a7d3.zip
      LayerName: "layer1"
  lf1spamham:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: lambdas-cloudformation
        S3Key: asm3.zip
      Description: lambda function for spam ham detection
      Environment:
        Variables:
          ENDPOINT_NAME: !Ref PredictionEndpoint
      FunctionName: lf1spamham
      Handler: LF1.lambda_handler
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - lf1spamhamrole
          - Arn
      Runtime: python3.8
      Timeout: 60
      Layers:
        - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python38-SciPy1x:107
        - !Ref LambdaLayer1
  SesRuleSet:
    Type: "AWS::SES::ReceiptRuleSet"
  SesRule:
    Type: "AWS::SES::ReceiptRule"
    Properties:
      Rule:
        Actions:
          - S3Action:
              BucketName: !Ref asm3emailfiles
        Enabled: true
        ScanEnabled: false
      RuleSetName: !Ref SesRuleSet
